/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejextras4poo;

import Entidades.Juego;

/**
 *
 * @author pablcastro3
 */
public class EjExtras4POO {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        Juego poker = new Juego();
        poker.iniciar_juego();
    }
    
}
